sonar.projectKey=aceest-fitness-gym
sonar.projectName=ACEest Fitness & Gym
sonar.projectVersion=3.2.4

sonar.sources=.
sonar.inclusions=app.py
sonar.tests=tests
sonar.test.inclusions=tests/test_app.py

sonar.language=python
sonar.python.version=3.12

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=test-results.xml

sonar.sourceEncoding=UTF-8
